// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLnD9zkG52gMYfnKUtClAELANi_RwIjHE',
    appId: '1:1089733084360:web:1f91e6ef5a864dee8611fd',
    messagingSenderId: '1089733084360',
    projectId: 'clone-b29a3',
    authDomain: 'clone-b29a3.firebaseapp.com',
    storageBucket: 'clone-b29a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWo0jvxFz_nWwovP79jfmzm6oBYoB_NY',
    appId: '1:1089733084360:android:145b168340127bff8611fd',
    messagingSenderId: '1089733084360',
    projectId: 'clone-b29a3',
    storageBucket: 'clone-b29a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0wAl-TIhQlxlSWolzQbT6d_3sqIB5lu8',
    appId: '1:1089733084360:ios:829de84b2734e0a18611fd',
    messagingSenderId: '1089733084360',
    projectId: 'clone-b29a3',
    storageBucket: 'clone-b29a3.appspot.com',
    iosBundleId: 'raghav.app.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0wAl-TIhQlxlSWolzQbT6d_3sqIB5lu8',
    appId: '1:1089733084360:ios:829de84b2734e0a18611fd',
    messagingSenderId: '1089733084360',
    projectId: 'clone-b29a3',
    storageBucket: 'clone-b29a3.appspot.com',
    iosBundleId: 'raghav.app.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLnD9zkG52gMYfnKUtClAELANi_RwIjHE',
    appId: '1:1089733084360:web:a91d208a7a4ede878611fd',
    messagingSenderId: '1089733084360',
    projectId: 'clone-b29a3',
    authDomain: 'clone-b29a3.firebaseapp.com',
    storageBucket: 'clone-b29a3.appspot.com',
  );
}
